### ISSUE TITLE
ORDER BY with params doesn't work

### ISSUE THREAD

**Issue by dmaechler** [thecodingmachine/magic-query#16] opened 2015-12-10 11:26 UTC
I try this unit test : 

```
 $sql = "SELECT id FROM users ORDER BY :order :direction";
        $this->assertEquals("SELECT id FROM users ORDER BY name ASC", self::simplifySql($magicQuery->build($sql, ['order' => 'name', 'direction' => 'ASC'])));

```

It doesn't work since the parser doesn't return the second parameter direction as an array of the ORDER key in the returned desc. The only item in ORDER section of the desc array returned by the parser is the first param and with a default direction that is ASC.

Plus there is a bug with the COLREF case in the NodeFactory for this case, indeed we try to do a $instance->setDirection($desc['direction']) while we have a Parameter object (:order).

**Comment by moufmouf** [comment] 2015-12-10 16:21
Actually, this is not supposed to work. The "order" parameter is supposed to be 'quoted' and be a constant, not a column name or a keyword.

Otherwise, we should also be able to do things like:

``` sql
SELECT :column FROM table
```

and this is clearly out of scope of any prepared statements.

**Comment by moufmouf** [comment] 2016-09-16 11:12
Closing this as this is not a bug.

**Closed as completed by moufmouf** 2016-09-16 11:12 UTC
