### ISSUE TITLE
Wrong parenthesis order with CASE

### ISSUE THREAD

**Issue by Zheness** [thecodingmachine/magic-query#73] opened 2020-09-03 10:13 UTC
Hello,

There a is a wrong order of parenthesis when a use a "CASE" followed with an alias.

Here is my initial mySQL query:
```sql
SELECT bar.foo, (CASE WHEN bar.foz = 1 THEN "ok" WHEN bar.hello = "world" THEN 2 ELSE 42 END) as status FROM bar
```

The MagicQuery change the parenthesis order **after the alias**, making the query wrong.

Here is the result after build:
```sql
SELECT `bar`.`foo`, ( CASE WHEN `bar`.`foz` = 1 THEN "ok" WHEN `bar`.`hello` = "world" THEN 2 ELSE 42 END AS status) FROM `bar`
```

Let me know if you have questions.

**Comment by moufmouf** [comment] 2020-09-03 14:19
This is already fixed in 1.4 (the issue is present in 1.3.0 only)

**Closed as completed by moufmouf** 2020-09-03 14:19 UTC
